### PR TITLE
Popup assignment

### PR DESCRIPTION
**Pull request by megha-n-bodke**
JS asks:

- a JavaScript array to store all of the information for all projects.
- pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to the source.
- projects section is created dynamically using the information stored in that JavaScript object. 
- HTML in that section is created when the page loads
- implement the popup window.

Interactions Implemented:

- user clicks (or taps) the close (X) button, and the popup disappears.
- the user clicks (or taps) the button to check project details, and the popup with details about the project appears.
- popups for both mobile and desktop screen sizes
- Closing issue
**NOTE:** I am working on my linter errors on the local machine, I have asked for help on slack. Please consider the above work.

### CODE REVIEW

**Review by tresorsawasawa — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @megha-n-bodke and @AmitKlohan 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has **Eslintrc** errors. Kindly make sure you fix them before requesting a new review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by megha-n-bodke** [comment]
@tresorsawasawa I have fixed all linting errors. 
Please review.

**Review by fobadara — CHANGES_REQUESTED** [review]
Hi @megha-n-bodke and @AmitKlohan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Linters are all green

## Required Changes ♻️
_Check the comments under the review._

- [ ] The entire project section is missing. It displays in your live demo but the button doesn't work (it probably displays because this is a live demo from a previous activity). But that section does not display in your current site commits.

Your current site
No-portfolio-section


Your live demo
no-popup-here


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

[OPTIONAL] Your README file can be better. For example, you should remove the `if available` beside your `live Demo` heading since you already know if you have a live demo or not. Also in major languages: flexbox and node are not languages. You should also tell us how to use your app in getting started: you could mention how to clone it,  edit the code and so on. This is an [example](https://github.com/fobadara/css-summit), it is not descriptive enough but a little bit better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by cwaku — APPROVED** [review]
Hi @megha-n-bodke and @aamirkhan2478 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 - [x] Good job overall following the template design 💯 
 - [x] Correct GitHub Flow 👍🏾 
 - [x] Good commit history 🥇 
 - [x] Good PR title/description 💯 
 - [x] All linters passed 🥇 
 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
